### ISSUE TITLE
Cannot import anything in route templates

### ISSUE THREAD

**Issue by MichalBryxi** [discourse/ember-route-template#20]
This on baffles me. Given following code:

```gts
// app/templates/application.gts

import RouteTemplate from 'ember-route-template';
import Component from '@glimmer/component';

// Imports are not preserved
import { t } from 'ember-intl';

// Comments are preserved
// import { pageTitle } from 'ember-page-title';

interface Signature {
  Args: {
    model: string;
  };
}

class ApplicationRoute extends Component<Signature> {
  <template>{{t 'bar'}}</template>
}

export default RouteTemplate(ApplicationRoute);
```

The app explodes with:

```
application.ts:28 Uncaught ReferenceError: t is not defined
    at Object.scope (application.ts:28:19)
    at meta (index.js:584:32)
    at compilable (index.js:1280:49)
    at TemplateImpl.asLayout (index.js:1445:54)
    at ConstantsImpl.component (index.js:130:617)
    at eval (index.js:181:26)
    at encodeOp (index.js:196:9)
    at pushOp (index.js:1296:5)
    at eval (index.js:1172:30)
    at Compilers.compile (index.js:536:114)
```

When I look into the compiled `application.ts` file from dev tools:

```
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
/* harmony import */ var ember_route_template__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ember-route-template */ "../../.pnpm/ember-route-template@1.0.3/node_modules/ember-route-template/dist/index.js");
/* harmony import */ var _glimmer_component__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @glimmer/component */ "../rewritten-packages/@glimmer/component.1ee13c05/node_modules/@glimmer/component/index.js");
/* harmony import */ var _ember_template_factory__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @ember/template-factory */ "../rewritten-packages/ember-source.066fca04/node_modules/ember-source/@ember/template-factory/index.js");
/* harmony import */ var _ember_component__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @ember/component */ "../rewritten-packages/ember-source.066fca04/node_modules/ember-source/@ember/component/index.js");
var _ApplicationRoute;


// Imports are not preserved

// Comments are preserved
// import { pageTitle } from 'ember-page-title';


class ApplicationRoute extends _glimmer_component__WEBPACK_IMPORTED_MODULE_1__["default"] {}
_ApplicationRoute = ApplicationRoute;
(0,_ember_component__WEBPACK_IMPORTED_MODULE_3__.setComponentTemplate)((0,_ember_template_factory__WEBPACK_IMPORTED_MODULE_2__.createTemplateFactory)(
/*
  {{t 'bar'}}
*/
{
  "id": "k6m6F70a",
  "block": "[[[1,[28,[32,0],[\"bar\"],null]]],[],false,[]]",
  "moduleName": "/Users/michal/flugmodus/node_modules/.embroider/rewritten-app/templates/application.ts",
  "scope": () => [t],
  "isStrictMode": true
}), _ApplicationRoute);
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ((0,ember_route_template__WEBPACK_IMPORTED_MODULE_0__["default"])(ApplicationRoute));

//# sourceURL=webpack://flugmodus/./templates/application.ts?
```

- Notice the comment `Imports are not preserved` and the line below (empty)
- Notice the comment `Comments are preserved` and the line below (still comment, so it's preserved)

**Comment by MichalBryxi** [comment]
I can put into the module scope anything I want (e.g: `const foo = '123';`) and it will be preserved in the compiled output. But any `import` statements get thrown away.

**Comment by MichalBryxi** [comment]
Update: I managed to make the app compile and (somewhat) work by adding following to `package.json` (assumes using `pnpm`):

```
  "pnpm": {
    "overrides": {
      "babel-plugin-ember-template-compilation": "2.3.0"
    }
  }
```

**Comment by chancancode** [comment]
Not sure what's going on here, but I think this is very likely filed in the wrong repository. This addon doesn't really do much, it just exports a normal function: https://github.com/discourse/ember-route-template/blob/main/ember-route-template/src/index.ts#L1-L18

It doesn't do anything with the build so it seems quite unlikely that using this addon is what caused the problem, unless, e.g. the app is not set up to use gts/gjs to begin with, or the setup specifically excluded the transformation from being applied in `app/templates` – those are essentially pre-requisites for using this addon.

It doesn't _enable_ gjs/gts transformation in `app/templates` by itself. It just solves the problem that – prior to ember-source 6.3, even if you have the transformation enabled, it would still fail at runtime because ember-source is expecting a raw template to be exported from these modules.

**Comment by MichalBryxi** [comment]
Hmm. Might be that some other package caused this, sorry. Wanted to document for the interwebs searches. The `package.json` at the time looked like this:

```
  "devDependencies": {
    "@babel/core": "^7.26.0",
    "@babel/eslint-parser": "^7.23.10",
    "@ember-data/adapter": "~5.4.0-beta.12",
    "@ember-data/graph": "~5.4.0-beta.12",
    "@ember-data/json-api": "~5.4.0-beta.12",
    "@ember-data/legacy-compat": "~5.4.0-beta.12",
    "@ember-data/model": "~5.4.0-beta.12",
    "@ember-data/request": "~5.4.0-beta.12",
    "@ember-data/request-utils": "~5.4.0-beta.12",
    "@ember-data/serializer": "~5.4.0-beta.12",
    "@ember-data/store": "~5.4.0-beta.12",
    "@ember-data/tracking": "~5.4.0-beta.12",
    "@ember/optional-features": "^2.2.0",
    "@ember/string": "^4.0.0",
    "@ember/test-helpers": "^4.0.4",
    "@embroider/compat": "^3.7.0",
    "@embroider/core": "^3.4.19",
    "@embroider/webpack": "^4.0.8",
    "@fortawesome/ember-fontawesome": "^1.0.3",
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/free-solid-svg-icons": "^6.4.2",
    "@frontile/buttons": "0.16.2",
    "@frontile/core": "0.16.2",
    "@frontile/overlays": "0.16.2",
    "@glimmer/component": "^1.1.2",
    "@glimmer/tracking": "^1.1.2",
    "@glint/core": "^1.5.0",
    "@glint/environment-ember-loose": "^1.5.0",
    "@glint/environment-ember-template-imports": "^1.5.0",
    "@glint/template": "^1.5.0",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/forms": "^0.5.4",
    "stylelint": "^15.11.0",
    "stylelint-config-standard": "^34.0.0",
    "stylelint-config-tailwindcss": "^0.0.7",
    "stylelint-prettier": "^4.1.0",
    "@tailwindcss/typography": "^0.5.10",
    "@tsconfig/ember": "^3.0.8",
    "@types/qunit": "^2.19.12",
    "@types/rsvp": "^4.0.9",
    "@typescript-eslint/eslint-plugin": "^7.18.0",
    "@typescript-eslint/parser": "^7.18.0",
    "@warp-drive/core-types": "~0.0.0-beta.12",
    "autoprefixer": "^10.4.15",
    "broccoli-asset-rev": "^3.0.0",
    "concurrently": "^8.2.2",
    "els-intl-addon": "^1.0.6",
    "ember-auto-import": "^2.10.0",
    "ember-cli": "~6.0.1",
    "ember-cli-app-version": "^7.0.0",
    "ember-cli-babel": "^8.2.0",
    "ember-cli-clean-css": "^3.0.0",
    "ember-cli-dependency-checker": "^3.3.2",
    "ember-cli-htmlbars": "^6.3.0",
    "ember-cli-image-transformer": "^7.0.0",
    "ember-cli-inject-live-reload": "^2.1.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-terser": "^4.0.2",
    "ember-css-transitions": "^4.4.0",
    "ember-fetch": "^8.1.2",
    "ember-intl": "6.0.0-beta.6",
    "ember-load-initializers": "^2.1.2",
    "ember-data": "~5.3.9",
    "ember-mobile-menu": "^5.1.0",
    "ember-modifier": "^4.2.0",
    "ember-page-title": "^8.2.3",
    "ember-qunit": "^8.1.1",
    "ember-resolver": "^12.0.1",
    "ember-responsive-image": "5.0.0-beta.0",
    "ember-route-template": "^1.0.3",
    "ember-source": "~6.0.0",
    "ember-template-imports": "^4.2.0",
    "ember-template-lint": "^6.0.0",
    "ember-web-app": "^5.0.1",
    "eslint": "^8.57.1",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-ember": "^12.3.1",
    "eslint-plugin-n": "^16.6.2",
    "eslint-plugin-prettier": "^5.2.1",
    "eslint-plugin-qunit": "^8.1.2",
    "loader.js": "^4.7.0",
    "postcss": "^8.4.27",
    "postcss-loader": "^7.3.3",
    "prettier": "^3.4.2",
    "prettier-plugin-ember-template-tag": "^2.0.4",
    "qunit": "^2.22.0",
    "qunit-dom": "^3.3.0",
    "tailwindcss": "^3.0.0",
    "tracked-built-ins": "^3.3.0",
    "typescript": "^5.6.3",
    "webpack": "^5.96.1"
  },
  "dependencies": {
    "@ember-responsive-image/webpack": "^0.0.0",
    "sharp": "^0.33.2"
  },
```

**Comment by MichalBryxi** [comment]
If this ever strikes again, I've created a [Discord thread here](https://discord.com/channels/480462759797063690/568935504288940056/1352680828873736264).
